#!/bin/ksh
#
#==>  WAM post-processing prad
#
#     Arno Behrens (May 2012)
#
#PBS -S /bin/sh
#PBS -N prad
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l place=scatter
#PBS -q ksd-test
#
set -k
WAMDIR=/data/behrens/mywave
WORK=/data/behrens/mywave/workdir
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Radiation_User .
cp ${WAMDIR}/abs/prad prad.exe
#
./prad.exe
mv Radiation_Prot ${WAMDIR}/dayfiles/prad_prot_c
rm Radiation_User prad.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
